version: '3.8'
services: 
  frontend:
    container_name: frontend
    image: nginx:latest
    ports:
      - "8081:80"
    depends_on:
      - backend
      - php
      - imageserver
    volumes:
      - ./frontend/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
  
  backend:
    container_name: backend
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./backend/:/app
    command: bash -c "npm install --save-dev nodemon  & npm install express cors mysql2 & npx nodemon index.js "
    working_dir: /app
    restart: always

  php:
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/var/www/html
    restart: always
  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mydatabase"
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306 
    ports:
      - "8082:80"
    depends_on:
      - db
    restart: always
  echo_cloud:
    image: cloudflare/cloudflared:latest
    container_name: echo_cloud
    command: tunnel --no-autoupdate run --token eyJhIjoiNzJmZGJjM2U2YjJlNGM1YTg4MWNhMDNiMTZhMDc5NTEiLCJ0IjoiOTY1Y2ZjM2QtNzFhYS00MWM0LTg2NzEtYjRmZGVmMWI1ZTRlIiwicyI6Ik5qSmhOMlUwWVdVdE9XUm1ZeTAwTnpBMkxXSXpNR0V0TnpJd09EY3paR1kxTUdNMSJ9
    restart: unless-stopped

