CREATE DATABASE IF NOT EXISTS echo;
USE echo;

CREATE TABLE IF NOT EXISTS users (
    user_id VARCHAR(255) PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    email VARCHAR(255) UNIQUE,
    `password` VARCHAR(255),
    active_status BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    profile_pic VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS post (
    id VARCHAR(255) PRIMARY KEY,
    user_id VARCHAR(255),
    caption TEXT,
    posted_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    image VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE
);